### ISSUE TITLE
Cannot find libglfw.so.3

### ISSUE THREAD

**Issue by J-Cake** [Reon90/glfwJS#2]
Hi it's me again :P

I've been playing around with the library for a little bit and it's worked, except now I can't start the application because of 

```
(node:52496) UnhandledPromiseRejectionWarning: Error: libglfw.so.3: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1251:18)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/usr/lib/lotus/native/glfwJS/generated/interface.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
```
I'd like to point out also that I had to modify the `/generated/interface.js` file at like 2 as node-gyp does not create a `/build/linux` directory, and it has worked so far. Otherwise, I haven't touched anything and I suddenly cannot use the library any more.

would you know what to do about it? I've been playing around with some build scripts for a little bit and can't seem to locate the issue :/

Thanks

**Comment by J-Cake** [comment]
It turns out there was no building required :D
